services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver2019
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - ./backup:/var/opt/mssql/backup
